POST http://localhost:3000/protected HTTP/1.1
Content-Type: multipart/form-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsInN1YiI6MiwiaWF0IjoxNjQyMTYxMzA0LCJleHAiOjE2NDIxNjEzNjR9.TQPS4XCA40CKeh9x8rZrWXoIP6Dt0oqKlHVkJ4l7CkE
